#!/usr/bin/env python

import sys

#from launch_buttons.launch_buttons_plugin import LaunchButtonsPlugin
from rqt_gui.main import Main

plugin = 'gui'
main = Main()
sys.exit(main.main(standalone=plugin))
