#!/usr/bin/env python

import sys
import inspect
import os

currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
final_path = os.path.join(parentdir, 'src')

sys.path.append(final_path)

from random_buttons.random_buttons_plugin import RandomButtonsPlugin
from rqt_gui.main import Main

plugin = 'random_buttons'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))