#!/usr/bin/env python

import sys

from gui.launch_buttons_plugin import LaunchButtonsPlugin
from rqt_gui.main import Main

plugin = 'gui/launch_buttons_plugin'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))